{
 "title": "Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT last(\"time\") FROM \"demo\"",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT last(\"cpu_usage\") FROM \"demo\"",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT last(\"disk_percent\") FROM \"demo\"",
     "select": [
      [
       { "params": [ "load_5" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT last(\"mem_percent\") FROM \"demo\"",
     "select": [
      [
       { "params": [ "mem_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT last(\"temperature\") FROM \"demo\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT mean(\"air_quality\") FROM \"demo\" GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "air_quality" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT mean(\"co_percent\") FROM \"demo\" GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "co_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "measurement": "demo",
     "query": "SELECT mean(\"room_temperature\") FROM \"demo\" GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "room_temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}